name: SDKs
on:
  push:
    tags:
      - v*
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - run: echo "Hello, world!"
  sdk:
    runs-on: ubuntu-latest
    name: Publish SDK
    strategy:
      matrix:
        name:
        - python
    steps:
      - uses: actions/checkout@v2
      - run: make --directory sdks/${{matrix.name}} publish -B
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
